Repository turbot/tdk, pull requests merged in 2020-05, with the labels that each got.

#86 Control Objective - Turbot Service Roles #111
  control_objectives/aws_iam_turbot_service_roles/README.md
  control_objectives/aws_iam_turbot_service_roles/default.tfvars
  control_objectives/aws_iam_turbot_service_roles/main.tf
  control_objectives/aws_iam_turbot_service_roles/variables.tf
Labels: enhancement

#87 Control Objective - RDS Audit Logging #112
  control_objectives/aws_rds_audit_logging/README.md
  control_objectives/aws_rds_audit_logging/default.tfvars
  control_objectives/aws_rds_audit_logging/main.tf
  control_objectives/aws_rds_audit_logging/variables.tf
Labels: enhancement

#91 Control Objective - Turbot IAM Roles #113
  control_objectives/turbot_iam_roles/README.md
  control_objectives/turbot_iam_roles/default.tfvars
  control_objectives/turbot_iam_roles/main.tf
  control_objectives/turbot_iam_roles/variables.tf
Labels: enhancement

#89 Control Objective - Restrict NAT Gateway within VPC #115
  control_objectives/aws_vpc_restrict_nat/README.md
  control_objectives/aws_vpc_restrict_nat/default.tfvars
  control_objectives/aws_vpc_restrict_nat/main.tf
  control_objectives/aws_vpc_restrict_nat/variables.tf
Labels: enhancement

#92 Installation - Updating workspace manager template #116
  installation/workspace-template.yml
Labels: enhancement

#88 Control Objective - S3 limit public access #117
  control_objectives/aws_s3_limit_public_access/README.md
  control_objectives/aws_s3_limit_public_access/default.tfvars
  control_objectives/aws_s3_limit_public_access/main.tf
  control_objectives/aws_s3_limit_public_access/variables.tf
Labels: enhancement

#119 Calculated Policy - Alarm if EC2 instance is in public subnet #129
  calculated_policies/aws_ec2_public_subnet/README.md
  calculated_policies/aws_ec2_public_subnet/default.tfvars
  calculated_policies/aws_ec2_public_subnet/main.tf
  calculated_policies/aws_ec2_public_subnet/variables.tf
Labels: enhancement

#104 GraphQL - Queries to filter activities/notifications #100
  api_examples/graphql/queries/list_notifications_for_controls_that_moved_to_alarm_state.graphql
  api_examples/graphql/queries/notifications/get_turbot_actor_id.graphql
  api_examples/graphql/queries/notifications/get_user_actor_id.graphql
  api_examples/graphql/queries/notifications/list_all_created_notifications_by_user.graphql
  api_examples/graphql/queries/notifications/list_all_created_notifications_excluding_user.graphql
  api_examples/graphql/queries/notifications/list_all_deleted_notifications_by_user.graphql
  api_examples/graphql/queries/notifications/list_all_deleted_notifications_excluding_user.graphql
  api_examples/graphql/queries/notifications/list_all_updated_notifications_by_user.graphql
  api_examples/graphql/queries/notifications/list_all_updated_notifications_excluding_user.graphql
  api_examples/graphql/queries/notifications/list_control_notifications_by_user.graphql
  api_examples/graphql/queries/notifications/list_control_notifications_excluding_user.graphql
  api_examples/graphql/queries/notifications/list_policy_setting_notifications_by_user.graphql
  api_examples/graphql/queries/notifications/list_policy_setting_notifications_excluding_user.graphql
  api_examples/graphql/queries/notifications/list_policy_value_notifications_by_user.graphql
  api_examples/graphql/queries/notifications/list_policy_value_notifications_excluding_user.graphql
  api_examples/graphql/queries/notifications/list_resource_notifications_by_user.graphql
  api_examples/graphql/queries/notifications/list_resource_notifications_excluding_user.graphql
Labels: enhancement

#135 Calculated Policies - Restrict cross-account access to Redshift snapshots #130
  .gitignore
  baselines/azure/azure-cis-v1/default.tfvars
  baselines/azure/azure_eventing/default.tfvars
  baselines/azure/azure_provider_registration/default.tfvars
  baselines/azure/azure_services/default.tfvars
  calculated_policies/aws_ec2_instance_age/variables.tf
  calculated_policies/aws_redshift_restrict_cross_account_snapshot_access/README.md
  calculated_policies/aws_redshift_restrict_cross_account_snapshot_access/default.tfvars
  calculated_policies/aws_redshift_restrict_cross_account_snapshot_access/main.tf
  calculated_policies/aws_redshift_restrict_cross_account_snapshot_access/variables.tf
  calculated_policies/aws_s3_bucket_tagging_template/variables.tf
  calculated_policies/aws_sqs_approved/variables.tf
  calculated_policies/azure_load_balancer_prohibited_ports/variables.tf
  calculated_policies/multi_cloud_storage_cost_savings/variables.tf
  control_objectives/s3_smartfolder_example/variables.tf
Labels: enhancement

#137 Create Calculated Policy README.md generator #136
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  repo-tools/README.md
  repo-tools/gen-doc-calc-policies.js
  repo-tools/package-lock.json
  repo-tools/package.json
  repo-tools/templates/calc-policy-template.njk
  repo-tools/templates/calc-policy/aws_redshift_restrict_cross_account_snapshot_access/template.yml
Labels: documentation, enhancement

#157 Repo Tools - Add safe string mode to rendering #156
  repo-tools/templates/calc-policy-template.njk
Labels: bug

#161 Calculated Policies - aws_sqs_approved returning incorrect value for not approved case #155
  calculated_policies/aws_redshift_restrict_cross_account_snapshot_access/default.tfvars
  calculated_policies/aws_redshift_restrict_cross_account_snapshot_access/variables.tf
  calculated_policies/aws_sqs_approved/README.md
  calculated_policies/aws_sqs_approved/default.tfvars
  calculated_policies/aws_sqs_approved/main.tf
  calculated_policies/aws_sqs_approved/variables.tf
  repo-tools/templates/calc-policy-template.njk
  repo-tools/templates/calc-policy/aws_sqs_approved/template.yml
Labels: bug

#165 Calculated Policy - Instance Approved if published by Approved Account #162
  calculated_policies/aws_ec2_instance_approved_usage_approved_account_ami/README.md
  calculated_policies/aws_ec2_instance_approved_usage_approved_account_ami/default.tfvars
  calculated_policies/aws_ec2_instance_approved_usage_approved_account_ami/main.tf
  calculated_policies/aws_ec2_instance_approved_usage_approved_account_ami/variables.tf
  repo-tools/templates/calc-policy/aws_ec2_instance_approved_usage_approved_account_ami/template.yml
Labels: enhancement

#164 Create a Calculated Policy to set Instance Approved if using Local AMI #153
  calculated_policies/aws_ec2_instance_approved_usage_local_ami/README.md
  calculated_policies/aws_ec2_instance_approved_usage_local_ami/default.tfvars
  calculated_policies/aws_ec2_instance_approved_usage_local_ami/main.tf
  calculated_policies/aws_ec2_instance_approved_usage_local_ami/variables.tf
  repo-tools/templates/calc-policy/aws_ec2_instance_approved_usage_local_ami/template.yml
Labels: enhancement

#146 Control Objective - Limit Elastic IPs in a VPC #168
  control_objectives/aws_vpc_elastic_ip_check/README.md
  control_objectives/aws_vpc_elastic_ip_check/default.tfvars
  control_objectives/aws_vpc_elastic_ip_check/main.tf
  control_objectives/aws_vpc_elastic_ip_check/variables.tf
Labels: enhancement

#145 Control Objective - RDS Public Access Check #169
  control_objectives/aws_rds_public_access/README.md
  control_objectives/aws_rds_public_access/default.tfvars
  control_objectives/aws_rds_public_access/main.tf
  control_objectives/aws_rds_public_access/variables.tf
Labels: enhancement

#143 Control Objective - AWS IAM Account Password Settings #170
  control_objectives/aws_iam_password_settings/README.md
  control_objectives/aws_iam_password_settings/default.tfvars
  control_objectives/aws_iam_password_settings/main.tf
  control_objectives/aws_iam_password_settings/variables.tf
Labels: enhancement

#142 Control Objective - Restrict IGW #171
  control_objectives/aws_vpc_restrict_igw/README.md
  control_objectives/aws_vpc_restrict_igw/default.tfvars
  control_objectives/aws_vpc_restrict_igw/main.tf
  control_objectives/aws_vpc_restrict_igw/variables.tf
Labels: enhancement

#141 Control Objective - Turbot AWS Event Handlers #172
  control_objectives/turbot_aws_event_handlers/README.md
  control_objectives/turbot_aws_event_handlers/default.tfvars
  control_objectives/turbot_aws_event_handlers/main.tf
  control_objectives/turbot_aws_event_handlers/variables.tf
Labels: enhancement

#140 Control Objective - RDS Storage Space Alarms #173
  control_objectives/aws_rds_storage_space_alarms/README.md
  control_objectives/aws_rds_storage_space_alarms/default.tfvars
  control_objectives/aws_rds_storage_space_alarms/main.tf
  control_objectives/aws_rds_storage_space_alarms/variables.tf
Labels: enhancement

#139 Control Objectives - Smart folder missing for calculated policy #174
  control_objectives/aws_ec2_instance_approved/main.tf
Labels: bug

#134 Calculated Policies - Fixed Turbot Terraform Provider weblink #175
  calculated_policies/aws_ec2_instance_age/README.md
  calculated_policies/aws_ec2_public_subnet/README.md
  calculated_policies/aws_lambda_in_vpc/README.md
  calculated_policies/aws_s3_bucket_tagging_template/README.md
  calculated_policies/aws_sqs_approved/README.md
  calculated_policies/azure_load_balancer_prohibited_ports/README.md
  calculated_policies/multi_cloud_storage_cost_savings/README.md
Labels: bug

#154 Calculated Policy - Restrict GuardDuty Detector master account #144
  calculated_policies/aws_guardduty_detector_approved_usage/README.md
  calculated_policies/aws_guardduty_detector_approved_usage/default.tfvars
  calculated_policies/aws_guardduty_detector_approved_usage/main.tf
  calculated_policies/aws_guardduty_detector_approved_usage/variables.tf
  repo-tools/templates/calc-policy/aws_guardduty_detector_approved_usage/template.yml
Labels: enhancement

#152 Calculated Policy - Restrict Lambda Cross Account Access #132
  calculated_policies/aws_lambda_not_approved_cross_account_access/README.md
  calculated_policies/aws_lambda_not_approved_cross_account_access/default.tfvars
  calculated_policies/aws_lambda_not_approved_cross_account_access/main.tf
  calculated_policies/aws_lambda_not_approved_cross_account_access/variables.tf
  repo-tools/templates/calc-policy/aws_lambda_not_approved_cross_account_access/template.yml
Labels: enhancement
