Repository turbot/tdk, pull requests merged in 2020-06, with the labels that each got.

#180 Documentation - Expand out calc policy template engine #159
  calculated_policies/aws_ec2_instance_age/README.md
  calculated_policies/aws_ec2_instance_approved_usage_approved_account_ami/README.md
  calculated_policies/aws_ec2_instance_approved_usage_approved_account_ami/variables.tf
  calculated_policies/aws_ec2_instance_approved_usage_local_ami/README.md
  calculated_policies/aws_ec2_instance_approved_usage_local_ami/main.tf
  calculated_policies/aws_ec2_instance_approved_usage_trusted_ami/README.md
  calculated_policies/aws_ec2_public_subnet/README.md
  calculated_policies/aws_guardduty_detector_approved_usage/README.md
  calculated_policies/aws_lambda_in_vpc/README.md
  calculated_policies/aws_lambda_not_approved_cross_account_access/README.md
  calculated_policies/aws_redshift_restrict_cross_account_snapshot_access/README.md
  calculated_policies/aws_redshift_restrict_cross_account_snapshot_access/main.tf
  calculated_policies/aws_s3_bucket_tagging_template/README.md
  calculated_policies/aws_sqs_approved/README.md
  calculated_policies/azure_load_balancer_prohibited_ports/README.md
  calculated_policies/multi_cloud_storage_cost_savings/README.md
  repo-tools/README.md
  repo-tools/gen-doc-calc-policies.js
  repo-tools/package-lock.json
  repo-tools/package.json
  repo-tools/templates/calc-policy/aws_ec2_instance_age/template.yml
  repo-tools/templates/calc-policy/aws_ec2_instance_approved_usage_approved_account_ami/template.yml
  repo-tools/templates/calc-policy/aws_ec2_instance_approved_usage_local_ami/template.yml
  repo-tools/templates/calc-policy/aws_ec2_instance_approved_usage_trusted_ami/template.yml
  repo-tools/templates/calc-policy/aws_ec2_public_subnet/template.yml
  repo-tools/templates/calc-policy/aws_guardduty_detector_approved_usage/template.yml
  repo-tools/templates/calc-policy/aws_lambda_in_vpc/template.yml
  repo-tools/templates/calc-policy/aws_redshift_restrict_cross_account_snapshot_access/template.yml
  repo-tools/templates/calc-policy/aws_s3_bucket_tagging_template/template.yml
  repo-tools/templates/calc-policy/aws_sqs_approved/template.yml
  repo-tools/templates/calc-policy/azure_load_balancer_prohibited_ports/template.yml
  repo-tools/templates/calc-policy/multi_cloud_storage_cost_savings/template.yml
  repo-tools/templates/calc-policy/template.njk
Labels: enhancement

#182 Calculated Policy - AWS > RDS > DB Cluster Snapshot [Manual] Cross Account Access #181
  calculated_policies/aws_rds_db_cluster_snapshot_cross_account_access/README.md
  calculated_policies/aws_rds_db_cluster_snapshot_cross_account_access/default.tfvars
  calculated_policies/aws_rds_db_cluster_snapshot_cross_account_access/main.tf
  calculated_policies/aws_rds_db_cluster_snapshot_cross_account_access/variables.tf
  repo-tools/templates/calc-policy/aws_rds_db_cluster_snapshot_cross_account_access/template.yml
Labels: enhancement

#196 Base Line - Update AWS Services list #123
  baselines/aws/aws_services/aws_service_list.txt
Labels: enhancement

#198 Documentation - Improve Calculated Policy Index Document #197
  baselines/README.md
  calculated_policies/README.md
  calculated_policies/aws_ec2_instance_age/README.md
  calculated_policies/aws_ec2_instance_age/main.tf
  calculated_policies/aws_ec2_instance_approved_usage_approved_account_ami/README.md
  calculated_policies/aws_ec2_instance_approved_usage_approved_account_ami/main.tf
  calculated_policies/aws_ec2_instance_approved_usage_local_ami/README.md
  calculated_policies/aws_ec2_instance_approved_usage_local_ami/main.tf
  calculated_policies/aws_ec2_instance_approved_usage_trusted_ami/README.md
  calculated_policies/aws_ec2_instance_approved_usage_trusted_ami/main.tf
  calculated_policies/aws_ec2_public_subnet/README.md
  calculated_policies/aws_ec2_public_subnet/main.tf
  calculated_policies/aws_guardduty_detector_approved_usage/README.md
  calculated_policies/aws_guardduty_detector_approved_usage/main.tf
  calculated_policies/aws_lambda_in_vpc/README.md
  calculated_policies/aws_lambda_in_vpc/main.tf
  calculated_policies/aws_lambda_not_approved_cross_account_access/README.md
  calculated_policies/aws_lambda_not_approved_cross_account_access/main.tf
  calculated_policies/aws_rds_db_cluster_snapshot_cross_account_access/README.md
  calculated_policies/aws_rds_db_cluster_snapshot_cross_account_access/main.tf
  calculated_policies/aws_redshift_restrict_cross_account_snapshot_access/README.md
  calculated_policies/aws_redshift_restrict_cross_account_snapshot_access/main.tf
  calculated_policies/aws_s3_approved_static_website_hosting_requires_cloud_front/README.md
  calculated_policies/aws_s3_approved_static_website_hosting_requires_cloud_front/main.tf
  calculated_policies/aws_s3_bucket_approved_usage_cross_account_replication/README.md
  calculated_policies/aws_s3_bucket_approved_usage_cross_account_replication/main.tf
  calculated_policies/aws_s3_bucket_approved_usage_name_dns_compliant/README.md
  calculated_policies/aws_s3_bucket_approved_usage_name_dns_compliant/main.tf
  calculated_policies/aws_s3_bucket_tagging_template/README.md
  calculated_policies/aws_s3_bucket_tagging_template/main.tf
  calculated_policies/aws_sqs_approved/README.md
  calculated_policies/aws_sqs_approved/main.tf
  calculated_policies/azure_load_balancer_prohibited_ports/README.md
  calculated_policies/azure_load_balancer_prohibited_ports/main.tf
  calculated_policies/multi_cloud_storage_cost_savings/README.md
  calculated_policies/multi_cloud_storage_cost_savings/main.tf
  repo-tools/gen-doc-calc-policies.js
  repo-tools/templates/calc-policy/aws_ec2_instance_age/template.yml
  repo-tools/templates/calc-policy/aws_ec2_instance_approved_usage_approved_account_ami/template.yml
  repo-tools/templates/calc-policy/aws_ec2_instance_approved_usage_local_ami/template.yml
  repo-tools/templates/calc-policy/aws_ec2_instance_approved_usage_trusted_ami/template.yml
  repo-tools/templates/calc-policy/aws_ec2_public_subnet/template.yml
  repo-tools/templates/calc-policy/aws_guardduty_detector_approved_usage/template.yml
  repo-tools/templates/calc-policy/aws_lambda_in_vpc/template.yml
  repo-tools/templates/calc-policy/aws_lambda_not_approved_cross_account_access/template.yml
  repo-tools/templates/calc-policy/aws_rds_db_cluster_snapshot_cross_account_access/template.yml
  repo-tools/templates/calc-policy/aws_redshift_restrict_cross_account_snapshot_access/template.yml
  repo-tools/templates/calc-policy/aws_s3_approved_static_website_hosting_requires_cloud_front/template.yml
  repo-tools/templates/calc-policy/aws_s3_bucket_approved_usage_cross_account_replication/template.yml
  repo-tools/templates/calc-policy/aws_s3_bucket_approved_usage_name_dns_compliant/template.yml
  repo-tools/templates/calc-policy/aws_s3_bucket_tagging_template/template.yml
  repo-tools/templates/calc-policy/aws_sqs_approved/template.yml
  repo-tools/templates/calc-policy/azure_load_balancer_prohibited_ports/template.yml
  repo-tools/templates/calc-policy/document.njk
  repo-tools/templates/calc-policy/index-document.njk
  repo-tools/templates/calc-policy/multi_cloud_storage_cost_savings/template.yml
Labels: enhancement

#201 Documentation - Give steps to run calculated policy in index file #199
  baselines/README.md
  calculated_policies/README.md
  repo-tools/templates/calc-policy/index-document.njk
Labels: enhancement

#189 Base Lines - Expand Azure eventing to allow for event type choices #103
  baselines/azure/azure_eventing/default.tfvars
  baselines/azure/azure_eventing/main.tf
  baselines/azure/azure_eventing/variables.tf
Labels: enhancement

#204 Calculated Policy - Azure > Storage > Container approved if access level is not public #203
  calculated_policies/README.md
  calculated_policies/azure_storage_container_approved_usage_not_public/README.md
  calculated_policies/azure_storage_container_approved_usage_not_public/default.tfvars
  calculated_policies/azure_storage_container_approved_usage_not_public/main.tf
  calculated_policies/azure_storage_container_approved_usage_not_public/variables.tf
  repo-tools/templates/calc-policy/azure_storage_container_approved_usage_not_public/template.yml
Labels: enhancement

#183 Control Objective - Restrict AWS IAM * action and inline policies #208
  control_objectives/aws_iam_restrict_policies/README.md
  control_objectives/aws_iam_restrict_policies/default.tfvars
  control_objectives/aws_iam_restrict_policies/main.tf
  control_objectives/aws_iam_restrict_policies/variables.tf
Labels: enhancement

#215 Calculated Policy - AWS > Redshift > Cluster - Approve if encryption in transit is required #176
  calculated_policies/README.md
  calculated_policies/aws_redshift_cluster_require_ssl/README.md
  calculated_policies/aws_redshift_cluster_require_ssl/default.tfvars
  calculated_policies/aws_redshift_cluster_require_ssl/main.tf
  calculated_policies/aws_redshift_cluster_require_ssl/variables.tf
  repo-tools/templates/calc-policy/aws_redshift_cluster_require_ssl/template.yml
Labels: enhancement

#218 API Examples - Running policies by state scripts #217
  api_examples/graphql/clients/node/run-controls-for-filter/run-controls-for-filter.js
  api_examples/graphql/clients/node/run-policies/README.md
  api_examples/graphql/clients/node/run-policies/package-lock.json
  api_examples/graphql/clients/node/run-policies/package.json
  api_examples/graphql/clients/node/run-policies/run-policies.js
  api_examples/graphql/clients/python/run_controls/run_controls.py
  api_examples/graphql/clients/python/run_policies/README.md
  api_examples/graphql/clients/python/run_policies/requirements.txt
  api_examples/graphql/clients/python/run_policies/run_policies.py
Labels: enhancement

#220 Calculated Policy - Azure > Compute > Disk approved if using customer key encryption #219
  calculated_policies/README.md
  calculated_policies/azure_compute_disk_approved_usage_customer_key_encrypted/README.md
  calculated_policies/azure_compute_disk_approved_usage_customer_key_encrypted/default.tfvars
  calculated_policies/azure_compute_disk_approved_usage_customer_key_encrypted/main.tf
  calculated_policies/azure_compute_disk_approved_usage_customer_key_encrypted/variables.tf
  repo-tools/templates/calc-policy/azure_compute_disk_approved_usage_customer_key_encrypted/template.yml
Labels: enhancement

#238 API Examples - Fix bugs in python index template #237
  api_examples/graphql/clients/python/README.md
  api_examples/graphql/clients/python/aws_import/README.md
  api_examples/graphql/clients/python/get-notifications-by-class/README.md
  api_examples/graphql/clients/python/get-notifications-by-type/README.md
  api_examples/graphql/clients/python/get-notifications-for-resource/README.md
  api_examples/graphql/clients/python/run_controls/README.md
  api_examples/graphql/clients/python/run_controls_batches/README.md
  api_examples/graphql/clients/python/run_policies/README.md
  api_examples/graphql/clients/python/run_policies_batches/README.md
  repo-tools/gen-doc-api-examples.js
  repo-tools/templates/api-examples/index-python.njk
  repo-tools/templates/api-examples/python.njk
Labels: bug, documentation

#240 API Examples - Add turbot library to document generator #239
  api_examples/graphql/clients/python/README.md
  api_examples/graphql/clients/python/aws_import/README.md
  api_examples/graphql/clients/python/get-notifications-by-class/README.md
  api_examples/graphql/clients/python/get-notifications-by-type/README.md
  api_examples/graphql/clients/python/get-notifications-for-resource/README.md
  api_examples/graphql/clients/python/run_controls/README.md
  api_examples/graphql/clients/python/run_controls_batches/README.md
  api_examples/graphql/clients/python/run_policies/README.md
  api_examples/graphql/clients/python/run_policies_batches/README.md
  api_examples/graphql/clients/python/turbot/README.md
  repo-tools/gen-doc-api-examples.js
  repo-tools/templates/api-examples/clients/python/turbot/template.yml
  repo-tools/templates/api-examples/python.njk
Labels: documentation, enhancement
